import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans'; 

import { Toaster, toast } from 'sonner'
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={GeistSans.className} suppressHydrationWarning>
      <body
        className={`antialiased` } 
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem >
          <div className="min-h-screen bg-background text-foreground">
            {children}
        <Toaster position="top-center" richColors closeButton />
          </div>
          
        </ThemeProvider>
      </body>
    </html>
  );
}
